### ISSUE TITLE
consider Scription support

### ISSUE THREAD

**Issue by dwhieb** [cldf/pyigt#16]
You might be interested in the scription format:

https://scription.digitallinguistics.io/

I've also written a JavaScript parser for it here:

https://developer.digitallinguistics.io/scription2dlx/

**Comment by xrotwang** [comment]
Yes, scription may be an alternative container format for IGT sentences, in addition to CLDF. Supporting it shouldn't be too difficult. AFAICT there aren't too many IGT collections in scription format around in the wild, though - similar to the situation with CLDF. Since most of my use cases involve IGT provided as examples in typological datasets, CLDF as source format seems more appropriate for me right now. Scription OTOH seems to be more a competitor for things like ELAN's XML format, right?

**Comment by dwhieb** [comment]
To be honest the motivation was more to formalize the interlinear format as it's already being used, in a way that made it computationally parseable, regardless of scripting language or output format after conversion (JSON, XML, etc.). You could just as easily write a scription > ELAN XML converter, or scription > CLDF etc.

**Comment by xrotwang** [comment]
Closing this until relevant IGT collections in Scription format are available.
