### ISSUE TITLE
Provide support for multiple languages

### ISSUE THREAD

**Issue by fmatter** [cldf/pyigt#7]
Do I assume correctly in that a single corpus is only supposed to contain examples from a single language (unlike structural datasets etc)? My CLDF examples setup contains glottocodes under the column `Language_ID`, but this seems to not matter to `pyigt`. I can easily create separate example databases for each language, if that is the way to do it.

**Comment by LinguList** [comment]
Actually, we never thought of the multi-language type, but it would probably be even nicer to also allow for that functionality. I even think it is not very difficult to do so, but we'll have to look into the code to see how much it will cost to come up with this. Could you, if possible, supply a CLDF example (also via email, or by pasting it as a zip file) of, say, two languages, so we can test them?

**Comment by fmatter** [comment]
There you go! Note that this is an example database for personal use, so it's not a "proper" shareable CLDF dataset, but I think it conforms to the CLDF format.

[linking_cldf_example.zip](https://github.com/cldf/pyigt/files/4496242/linking_cldf_example.zip)

**Comment by xrotwang** [comment]
@fmatter What would you consider "full multi-language support"? Additional columns from an examples file are already accessible from the `IGT` instances, see
```python
>>> from pyigt import Corpus
>>> crp = Corpus.from_path('tests/fixtures/examples.csv')
>>> igt = list(crp)[0]
>>> igt.properties['Language_ID']
... 'qiang'
```

But I'd agree that this does not take into account any CLDF semantics, so maybe - for the case that IGTs are read from a CLDF dataset - the column names should be translated to CLDF ontology names, e.g. `lannguageReference` instead of `Language_ID`. And maybe these translated properties should be available as an additional `dict` attribute `IGT.cldf`? Considering that we can only discover gloss, etc. using CLDF semantics, this seems appropriate.

**Comment by xrotwang** [comment]
Ping @fmatter Is the proposal in https://github.com/cldf/pyigt/issues/7#issuecomment-616518057 sufficient for your case? Or would you like to see other functionality added?

**Comment by fmatter** [comment]
I'll get back to you tonight!

**Comment by fmatter** [comment]
Ok, so I've looked at it again and I think what I was referencing in the original comment was about the grammatical and lexical concordances, which could a) contain an additional column `Language_ID`, and/or b) could be specified to only include a single language. Right now I get one file containing all morphemes from all languages.

Also, something like `corpus["LanguageTable"]` would be handy.

**Comment by xrotwang** [comment]
Ah, I see. Ok, adding `Language_ID` - or better `languageReference` to the concordances seems like a good idea. I wouldn't want to turn `Corpus` into a subclass of `pycldf.Dataset`, though, because as it is, it will also be usable with "stabdalone" examples files. But if you instantiated your `Corpus` from a CLDF dataset, you'd have the CLDF dataset's `LanguageTable` available anyway; and being able to reference it using an `IGT`'s `.cldf['languageReference']` would be all that's needed, right?

**Comment by fmatter** [comment]
> But if you instantiated your Corpus from a CLDF dataset, you'd have the CLDF dataset's LanguageTable available anyway; 

Would I have that available within `pyigt` if I used `from_cldf()`? Or how would I access the list of languages found in the CLDF example corpus?

But yes, differentiating languages in the output and having a language table handy somewhere is all that would be needed (from my view).

**Comment by xrotwang** [comment]
I'd imagine typical usage would look as follows:
```python
from pycldf import Dataset
from pyigt import Corpus

ds = Dataset.from_metadata('path/to/metadata.json')
corpus = Corpus.from_cldf(ds)
languages = {l[ds['LanguageTable', 'languageReference'].name]: l for l in ds['LanguageTable']}
for igt in corpus:
    print(languages[igt.cldf['languageReference']][ds['LanguageTable', 'name'].name])
```

Note that this is the generic version, where the code has no prior knowledge of the particular column names in the data files.

**Comment by fmatter** [comment]
Right, `Corpus.from_cldf(ds)` makes sense, thanks! But then why not just

`languages = {l["Name"]: l for l in ds['LanguageTable']}` 

(or `l["Language_ID"]`)?

**Comment by xrotwang** [comment]
If the calling code know the names of the columns, it can be simplified (as you propose above). For code that needs to work with generic CLDF datasets that is not the case, i.e. column names must be looked up in the metadata, using the `propertyUrl` (or as shorthand the local part) as lookup key. This lookup is done via
```python
ds[TABLE, LOCAL_NAME_OF_PROPERTY_URL]
```
i.e. calling `pycldf.Dataset.__getitem__`. This will return a `Column` object, and the `name` attribute is the actual column name.

While this seems a bit awkward, it is the price we had to pay to get around endless "the column should be called X" fights :)
