### ISSUE TITLE
How is the automated orthography profile created?

### ISSUE THREAD

**Issue by fmatter** [cldf/pyigt#8]
I rebuilt the example workflow from your Qiang texts example.

`texts.get_profile(clts=args.clts.api, filename=ds.dir / 'output' / 'automated-orthography.tsv')`

created an orthography profile. I copied it to `etc/orthography.tsv` and adjusted it. I had to tell it that `gw` was not a single segment, i.e., delete the whole row. On the other hand, I had to insert three rows (initial, central, end) telling it that `ng` was IPA `ŋ`. I had to to the same with `tx` (`t͡ʃ`). 

Why did it assume that `gw` was a segment?

And: is it necessary to define `^ng`, `ng`, `ng$` etc.?

**Comment by xrotwang** [comment]
That's a lingpy routine, called from `pyigt`. AFAIK it adds some common multi-character graphemes, since "splitting later" is simpler than "merging later", in particular since the latter is more likely to go undetected.
It seem `ng` and `tx` are not considered common. Right, @LinguList ?

**Comment by LinguList** [comment]
The algorithm is called [ipa2tokens](http://lingpy.org/reference/lingpy.sequence.html#lingpy.sequence.sound_classes.ipa2tokens). From the spec, you can see that it takes as arguments:

- diacritics
- tones
- vowels
- combiners
- semi_diacritics

The latter are what we have here: "h" when used with a consonant often means aspiration, so it clusters theres.

The full function is called [context_profile](http://lingpy.org/reference/lingpy.sequence.html#module-lingpy.sequence.profile) and makes some happy guessing. These things can be freely modified, but not within command-line workflow, so you'd have to write a script yourself. 

It is explicitly meant as a quick-and-dirty preprocessing, adding `ng` there would be difficult for the whole routine. If you use a context profile, you have to be careful and always, to be sure, repeat all "normal characters" with prefix `^`, since the greediness of the orthoprofile algorithm will otherwise yield unforeseen (but logical) things. You can check the algorithm in a JS version I wrote [here](https://digling.org/calc/profile/)

You don't need to delete a full line, you can also just replace `gw` by `g w`. This has turned out to be quite efficient for creating orthoprofiles in the past.

**Comment by fmatter** [comment]
> The full function is called context_profile and makes some happy guessing.

Ah! That explains a lot. 

> You don't need to delete a full line, you can also just replace gw by g w. This has turned out to be quite efficient for creating orthoprofiles in the past.

Good to know, thanks.
